#ifndef INCLUDE_MCMINI_TRANSITIONS_WRAPPERS_MCBANKACCOUNTWRAPPERS_HPP
#define INCLUDE_MCMINI_TRANSITIONS_WRAPPERS_MCBANKACCOUNTWRAPPERS_HPP

#include "mcmini/MCShared.h"

MC_EXTERN void mc_increment_bank_account(int *, int);
MC_EXTERN void mc_decrement_bank_account(int *, int);

#endif // INCLUDE_MCMINI_TRANSITIONS_WRAPPERS_MCBANKACCOUNTWRAPPERS_HPP
